//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int LogID { get; set; }
        public int EmployeeID { get; set; }
        public string ActionDescription { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
