//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int GuestID { get; set; }
        public int RoomID { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
